/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalEscalaRouteImport } from './routes/portal.escala'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalPendenciasRouteImport } from './routes/portal.pendencias'
import { Route as PortalPerfilRouteImport } from './routes/portal.perfil'
import { Route as PortalPontoRouteImport } from './routes/portal.ponto'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppDeliveryRulesRouteImport } from './routes/_authenticated/app.delivery-rules'
import { Route as AuthenticatedAppEmployeesRouteImport } from './routes/_authenticated/app.employees'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated/app.inventory'
import { Route as AuthenticatedAppItemsRouteImport } from './routes/_authenticated/app.items'
import { Route as AuthenticatedAppRolesTeamsRouteImport } from './routes/_authenticated/app.roles-teams'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated/app.sales'
import { Route as AuthenticatedAppScheduleComplianceRouteImport } from './routes/_authenticated/app.schedule-compliance'
import { Route as AuthenticatedAppScheduleHistoryRouteImport } from './routes/_authenticated/app.schedule-history'
import { Route as AuthenticatedAppScheduleTemplatesRouteImport } from './routes/_authenticated/app.schedule-templates'
import { Route as AuthenticatedAppSchedulesRouteImport } from './routes/_authenticated/app.schedules'
import { Route as AuthenticatedAppShiftsRouteImport } from './routes/_authenticated/app.shifts'
import { Route as AuthenticatedAppTimeEntriesRouteImport } from './routes/_authenticated/app.time-entries'
import { Route as AuthenticatedAppUnitsRouteImport } from './routes/_authenticated/app.units'
import { Route as ApiPublicSalesIngestRouteImport } from './routes/api/public/sales-ingest'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as PortalCartaoPontoIndexRouteImport } from './routes/portal.cartao-ponto.index'
import { Route as PortalCartaoPontoIdRouteImport } from './routes/portal.cartao-ponto.$id'
import { Route as PortalDocumentosIndexRouteImport } from './routes/portal.documentos.index'
import { Route as PortalDocumentosIdRouteImport } from './routes/portal.documentos.$id'
import { Route as PortalHoleritesIndexRouteImport } from './routes/portal.holerites.index'
import { Route as PortalHoleritesIdRouteImport } from './routes/portal.holerites.$id'
import { Route as PortalItensIndexRouteImport } from './routes/portal.itens.index'
import { Route as PortalItensIdRouteImport } from './routes/portal.itens.$id'
import { Route as AuthenticatedAppConformidadeIndexRouteImport } from './routes/_authenticated/app.conformidade.index'
import { Route as AuthenticatedAppConformidadeKitsRouteImport } from './routes/_authenticated/app.conformidade.kits'
import { Route as AuthenticatedAppConformidadePendenciasRouteImport } from './routes/_authenticated/app.conformidade.pendencias'
import { Route as AuthenticatedAppConformidadeTrocasRouteImport } from './routes/_authenticated/app.conformidade.trocas'
import { Route as AuthenticatedAppDeliveriesIndexRouteImport } from './routes/_authenticated/app.deliveries.index'
import { Route as AuthenticatedAppDeliveriesIdRouteImport } from './routes/_authenticated/app.deliveries.$id'
import { Route as AuthenticatedAppPointCardsIndexRouteImport } from './routes/_authenticated/app.point-cards.index'
import { Route as AuthenticatedAppPointCardsIdRouteImport } from './routes/_authenticated/app.point-cards.$id'
import { Route as AuthenticatedAppSettingsAceiteRouteImport } from './routes/_authenticated/app.settings.aceite'
import { Route as AuthenticatedAppSettingsLgpdRouteImport } from './routes/_authenticated/app.settings.lgpd'
import { Route as PortalHoleritesIdComprovanteRouteImport } from './routes/portal.holerites.$id.comprovante'
import { Route as AuthenticatedAppConformidadeExamesIndexRouteImport } from './routes/_authenticated/app.conformidade.exames.index'
import { Route as AuthenticatedAppConformidadeExamesIdRouteImport } from './routes/_authenticated/app.conformidade.exames.$id'
import { Route as AuthenticatedAppConformidadeExamesNovoRouteImport } from './routes/_authenticated/app.conformidade.exames.novo'
import { Route as AuthenticatedAppDocumentosHoleritesIndexRouteImport } from './routes/_authenticated/app.documentos.holerites.index'
import { Route as AuthenticatedAppDocumentosHoleritesIdRouteImport } from './routes/_authenticated/app.documentos.holerites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEscalaRoute = PortalEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPendenciasRoute = PortalPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPerfilRoute = PortalPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPontoRoute = PortalPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDeliveryRulesRoute =
  AuthenticatedAppDeliveryRulesRouteImport.update({
    id: '/delivery-rules',
    path: '/delivery-rules',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEmployeesRoute =
  AuthenticatedAppEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppItemsRoute = AuthenticatedAppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRolesTeamsRoute =
  AuthenticatedAppRolesTeamsRouteImport.update({
    id: '/roles-teams',
    path: '/roles-teams',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScheduleComplianceRoute =
  AuthenticatedAppScheduleComplianceRouteImport.update({
    id: '/schedule-compliance',
    path: '/schedule-compliance',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScheduleHistoryRoute =
  AuthenticatedAppScheduleHistoryRouteImport.update({
    id: '/schedule-history',
    path: '/schedule-history',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppScheduleTemplatesRoute =
  AuthenticatedAppScheduleTemplatesRouteImport.update({
    id: '/schedule-templates',
    path: '/schedule-templates',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSchedulesRoute =
  AuthenticatedAppSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppShiftsRoute = AuthenticatedAppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTimeEntriesRoute =
  AuthenticatedAppTimeEntriesRouteImport.update({
    id: '/time-entries',
    path: '/time-entries',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUnitsRoute = AuthenticatedAppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicSalesIngestRoute = ApiPublicSalesIngestRouteImport.update({
  id: '/api/public/sales-ingest',
  path: '/api/public/sales-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalCartaoPontoIndexRoute = PortalCartaoPontoIndexRouteImport.update({
  id: '/cartao-ponto/',
  path: '/cartao-ponto/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCartaoPontoIdRoute = PortalCartaoPontoIdRouteImport.update({
  id: '/cartao-ponto/$id',
  path: '/cartao-ponto/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosIndexRoute = PortalDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosIdRoute = PortalDocumentosIdRouteImport.update({
  id: '/documentos/$id',
  path: '/documentos/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHoleritesIndexRoute = PortalHoleritesIndexRouteImport.update({
  id: '/holerites/',
  path: '/holerites/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHoleritesIdRoute = PortalHoleritesIdRouteImport.update({
  id: '/holerites/$id',
  path: '/holerites/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalItensIndexRoute = PortalItensIndexRouteImport.update({
  id: '/itens/',
  path: '/itens/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalItensIdRoute = PortalItensIdRouteImport.update({
  id: '/itens/$id',
  path: '/itens/$id',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedAppConformidadeIndexRoute =
  AuthenticatedAppConformidadeIndexRouteImport.update({
    id: '/conformidade/',
    path: '/conformidade/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConformidadeKitsRoute =
  AuthenticatedAppConformidadeKitsRouteImport.update({
    id: '/conformidade/kits',
    path: '/conformidade/kits',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConformidadePendenciasRoute =
  AuthenticatedAppConformidadePendenciasRouteImport.update({
    id: '/conformidade/pendencias',
    path: '/conformidade/pendencias',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConformidadeTrocasRoute =
  AuthenticatedAppConformidadeTrocasRouteImport.update({
    id: '/conformidade/trocas',
    path: '/conformidade/trocas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDeliveriesIndexRoute =
  AuthenticatedAppDeliveriesIndexRouteImport.update({
    id: '/deliveries/',
    path: '/deliveries/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDeliveriesIdRoute =
  AuthenticatedAppDeliveriesIdRouteImport.update({
    id: '/deliveries/$id',
    path: '/deliveries/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPointCardsIndexRoute =
  AuthenticatedAppPointCardsIndexRouteImport.update({
    id: '/point-cards/',
    path: '/point-cards/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPointCardsIdRoute =
  AuthenticatedAppPointCardsIdRouteImport.update({
    id: '/point-cards/$id',
    path: '/point-cards/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsAceiteRoute =
  AuthenticatedAppSettingsAceiteRouteImport.update({
    id: '/settings/aceite',
    path: '/settings/aceite',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsLgpdRoute =
  AuthenticatedAppSettingsLgpdRouteImport.update({
    id: '/settings/lgpd',
    path: '/settings/lgpd',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const PortalHoleritesIdComprovanteRoute =
  PortalHoleritesIdComprovanteRouteImport.update({
    id: '/comprovante',
    path: '/comprovante',
    getParentRoute: () => PortalHoleritesIdRoute,
  } as any)
const AuthenticatedAppConformidadeExamesIndexRoute =
  AuthenticatedAppConformidadeExamesIndexRouteImport.update({
    id: '/conformidade/exames/',
    path: '/conformidade/exames/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConformidadeExamesIdRoute =
  AuthenticatedAppConformidadeExamesIdRouteImport.update({
    id: '/conformidade/exames/$id',
    path: '/conformidade/exames/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConformidadeExamesNovoRoute =
  AuthenticatedAppConformidadeExamesNovoRouteImport.update({
    id: '/conformidade/exames/novo',
    path: '/conformidade/exames/novo',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosHoleritesIndexRoute =
  AuthenticatedAppDocumentosHoleritesIndexRouteImport.update({
    id: '/documentos/holerites/',
    path: '/documentos/holerites/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentosHoleritesIdRoute =
  AuthenticatedAppDocumentosHoleritesIdRouteImport.update({
    id: '/documentos/holerites/$id',
    path: '/documentos/holerites/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portal/escala': typeof PortalEscalaRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/pendencias': typeof PortalPendenciasRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/ponto': typeof PortalPontoRoute
  '/portal/': typeof PortalIndexRoute
  '/app/delivery-rules': typeof AuthenticatedAppDeliveryRulesRoute
  '/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/app/items': typeof AuthenticatedAppItemsRoute
  '/app/roles-teams': typeof AuthenticatedAppRolesTeamsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/schedule-compliance': typeof AuthenticatedAppScheduleComplianceRoute
  '/app/schedule-history': typeof AuthenticatedAppScheduleHistoryRoute
  '/app/schedule-templates': typeof AuthenticatedAppScheduleTemplatesRoute
  '/app/schedules': typeof AuthenticatedAppSchedulesRoute
  '/app/shifts': typeof AuthenticatedAppShiftsRoute
  '/app/time-entries': typeof AuthenticatedAppTimeEntriesRoute
  '/app/units': typeof AuthenticatedAppUnitsRoute
  '/api/public/sales-ingest': typeof ApiPublicSalesIngestRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/portal/cartao-ponto/$id': typeof PortalCartaoPontoIdRoute
  '/portal/documentos/$id': typeof PortalDocumentosIdRoute
  '/portal/holerites/$id': typeof PortalHoleritesIdRouteWithChildren
  '/portal/itens/$id': typeof PortalItensIdRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/portal/cartao-ponto/': typeof PortalCartaoPontoIndexRoute
  '/portal/documentos/': typeof PortalDocumentosIndexRoute
  '/portal/holerites/': typeof PortalHoleritesIndexRoute
  '/portal/itens/': typeof PortalItensIndexRoute
  '/app/conformidade/kits': typeof AuthenticatedAppConformidadeKitsRoute
  '/app/conformidade/pendencias': typeof AuthenticatedAppConformidadePendenciasRoute
  '/app/conformidade/trocas': typeof AuthenticatedAppConformidadeTrocasRoute
  '/app/deliveries/$id': typeof AuthenticatedAppDeliveriesIdRoute
  '/app/point-cards/$id': typeof AuthenticatedAppPointCardsIdRoute
  '/app/settings/aceite': typeof AuthenticatedAppSettingsAceiteRoute
  '/app/settings/lgpd': typeof AuthenticatedAppSettingsLgpdRoute
  '/portal/holerites/$id/comprovante': typeof PortalHoleritesIdComprovanteRoute
  '/app/conformidade/': typeof AuthenticatedAppConformidadeIndexRoute
  '/app/deliveries/': typeof AuthenticatedAppDeliveriesIndexRoute
  '/app/point-cards/': typeof AuthenticatedAppPointCardsIndexRoute
  '/app/conformidade/exames/$id': typeof AuthenticatedAppConformidadeExamesIdRoute
  '/app/conformidade/exames/novo': typeof AuthenticatedAppConformidadeExamesNovoRoute
  '/app/documentos/holerites/$id': typeof AuthenticatedAppDocumentosHoleritesIdRoute
  '/app/conformidade/exames/': typeof AuthenticatedAppConformidadeExamesIndexRoute
  '/app/documentos/holerites/': typeof AuthenticatedAppDocumentosHoleritesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/portal/escala': typeof PortalEscalaRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/pendencias': typeof PortalPendenciasRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/ponto': typeof PortalPontoRoute
  '/portal': typeof PortalIndexRoute
  '/app/delivery-rules': typeof AuthenticatedAppDeliveryRulesRoute
  '/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/app/items': typeof AuthenticatedAppItemsRoute
  '/app/roles-teams': typeof AuthenticatedAppRolesTeamsRoute
  '/app/sales': typeof AuthenticatedAppSalesRoute
  '/app/schedule-compliance': typeof AuthenticatedAppScheduleComplianceRoute
  '/app/schedule-history': typeof AuthenticatedAppScheduleHistoryRoute
  '/app/schedule-templates': typeof AuthenticatedAppScheduleTemplatesRoute
  '/app/schedules': typeof AuthenticatedAppSchedulesRoute
  '/app/shifts': typeof AuthenticatedAppShiftsRoute
  '/app/time-entries': typeof AuthenticatedAppTimeEntriesRoute
  '/app/units': typeof AuthenticatedAppUnitsRoute
  '/api/public/sales-ingest': typeof ApiPublicSalesIngestRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/portal/cartao-ponto/$id': typeof PortalCartaoPontoIdRoute
  '/portal/documentos/$id': typeof PortalDocumentosIdRoute
  '/portal/holerites/$id': typeof PortalHoleritesIdRouteWithChildren
  '/portal/itens/$id': typeof PortalItensIdRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/portal/cartao-ponto': typeof PortalCartaoPontoIndexRoute
  '/portal/documentos': typeof PortalDocumentosIndexRoute
  '/portal/holerites': typeof PortalHoleritesIndexRoute
  '/portal/itens': typeof PortalItensIndexRoute
  '/app/conformidade/kits': typeof AuthenticatedAppConformidadeKitsRoute
  '/app/conformidade/pendencias': typeof AuthenticatedAppConformidadePendenciasRoute
  '/app/conformidade/trocas': typeof AuthenticatedAppConformidadeTrocasRoute
  '/app/deliveries/$id': typeof AuthenticatedAppDeliveriesIdRoute
  '/app/point-cards/$id': typeof AuthenticatedAppPointCardsIdRoute
  '/app/settings/aceite': typeof AuthenticatedAppSettingsAceiteRoute
  '/app/settings/lgpd': typeof AuthenticatedAppSettingsLgpdRoute
  '/portal/holerites/$id/comprovante': typeof PortalHoleritesIdComprovanteRoute
  '/app/conformidade': typeof AuthenticatedAppConformidadeIndexRoute
  '/app/deliveries': typeof AuthenticatedAppDeliveriesIndexRoute
  '/app/point-cards': typeof AuthenticatedAppPointCardsIndexRoute
  '/app/conformidade/exames/$id': typeof AuthenticatedAppConformidadeExamesIdRoute
  '/app/conformidade/exames/novo': typeof AuthenticatedAppConformidadeExamesNovoRoute
  '/app/documentos/holerites/$id': typeof AuthenticatedAppDocumentosHoleritesIdRoute
  '/app/conformidade/exames': typeof AuthenticatedAppConformidadeExamesIndexRoute
  '/app/documentos/holerites': typeof AuthenticatedAppDocumentosHoleritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/portal/escala': typeof PortalEscalaRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/pendencias': typeof PortalPendenciasRoute
  '/portal/perfil': typeof PortalPerfilRoute
  '/portal/ponto': typeof PortalPontoRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/app/delivery-rules': typeof AuthenticatedAppDeliveryRulesRoute
  '/_authenticated/app/employees': typeof AuthenticatedAppEmployeesRoute
  '/_authenticated/app/inventory': typeof AuthenticatedAppInventoryRoute
  '/_authenticated/app/items': typeof AuthenticatedAppItemsRoute
  '/_authenticated/app/roles-teams': typeof AuthenticatedAppRolesTeamsRoute
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRoute
  '/_authenticated/app/schedule-compliance': typeof AuthenticatedAppScheduleComplianceRoute
  '/_authenticated/app/schedule-history': typeof AuthenticatedAppScheduleHistoryRoute
  '/_authenticated/app/schedule-templates': typeof AuthenticatedAppScheduleTemplatesRoute
  '/_authenticated/app/schedules': typeof AuthenticatedAppSchedulesRoute
  '/_authenticated/app/shifts': typeof AuthenticatedAppShiftsRoute
  '/_authenticated/app/time-entries': typeof AuthenticatedAppTimeEntriesRoute
  '/_authenticated/app/units': typeof AuthenticatedAppUnitsRoute
  '/api/public/sales-ingest': typeof ApiPublicSalesIngestRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/portal/cartao-ponto/$id': typeof PortalCartaoPontoIdRoute
  '/portal/documentos/$id': typeof PortalDocumentosIdRoute
  '/portal/holerites/$id': typeof PortalHoleritesIdRouteWithChildren
  '/portal/itens/$id': typeof PortalItensIdRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/portal/cartao-ponto/': typeof PortalCartaoPontoIndexRoute
  '/portal/documentos/': typeof PortalDocumentosIndexRoute
  '/portal/holerites/': typeof PortalHoleritesIndexRoute
  '/portal/itens/': typeof PortalItensIndexRoute
  '/_authenticated/app/conformidade/kits': typeof AuthenticatedAppConformidadeKitsRoute
  '/_authenticated/app/conformidade/pendencias': typeof AuthenticatedAppConformidadePendenciasRoute
  '/_authenticated/app/conformidade/trocas': typeof AuthenticatedAppConformidadeTrocasRoute
  '/_authenticated/app/deliveries/$id': typeof AuthenticatedAppDeliveriesIdRoute
  '/_authenticated/app/point-cards/$id': typeof AuthenticatedAppPointCardsIdRoute
  '/_authenticated/app/settings/aceite': typeof AuthenticatedAppSettingsAceiteRoute
  '/_authenticated/app/settings/lgpd': typeof AuthenticatedAppSettingsLgpdRoute
  '/portal/holerites/$id/comprovante': typeof PortalHoleritesIdComprovanteRoute
  '/_authenticated/app/conformidade/': typeof AuthenticatedAppConformidadeIndexRoute
  '/_authenticated/app/deliveries/': typeof AuthenticatedAppDeliveriesIndexRoute
  '/_authenticated/app/point-cards/': typeof AuthenticatedAppPointCardsIndexRoute
  '/_authenticated/app/conformidade/exames/$id': typeof AuthenticatedAppConformidadeExamesIdRoute
  '/_authenticated/app/conformidade/exames/novo': typeof AuthenticatedAppConformidadeExamesNovoRoute
  '/_authenticated/app/documentos/holerites/$id': typeof AuthenticatedAppDocumentosHoleritesIdRoute
  '/_authenticated/app/conformidade/exames/': typeof AuthenticatedAppConformidadeExamesIndexRoute
  '/_authenticated/app/documentos/holerites/': typeof AuthenticatedAppDocumentosHoleritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/app'
    | '/onboarding'
    | '/portal/escala'
    | '/portal/login'
    | '/portal/pendencias'
    | '/portal/perfil'
    | '/portal/ponto'
    | '/portal/'
    | '/app/delivery-rules'
    | '/app/employees'
    | '/app/inventory'
    | '/app/items'
    | '/app/roles-teams'
    | '/app/sales'
    | '/app/schedule-compliance'
    | '/app/schedule-history'
    | '/app/schedule-templates'
    | '/app/schedules'
    | '/app/shifts'
    | '/app/time-entries'
    | '/app/units'
    | '/api/public/sales-ingest'
    | '/api/public/stripe-webhook'
    | '/portal/cartao-ponto/$id'
    | '/portal/documentos/$id'
    | '/portal/holerites/$id'
    | '/portal/itens/$id'
    | '/app/'
    | '/portal/cartao-ponto/'
    | '/portal/documentos/'
    | '/portal/holerites/'
    | '/portal/itens/'
    | '/app/conformidade/kits'
    | '/app/conformidade/pendencias'
    | '/app/conformidade/trocas'
    | '/app/deliveries/$id'
    | '/app/point-cards/$id'
    | '/app/settings/aceite'
    | '/app/settings/lgpd'
    | '/portal/holerites/$id/comprovante'
    | '/app/conformidade/'
    | '/app/deliveries/'
    | '/app/point-cards/'
    | '/app/conformidade/exames/$id'
    | '/app/conformidade/exames/novo'
    | '/app/documentos/holerites/$id'
    | '/app/conformidade/exames/'
    | '/app/documentos/holerites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/portal/escala'
    | '/portal/login'
    | '/portal/pendencias'
    | '/portal/perfil'
    | '/portal/ponto'
    | '/portal'
    | '/app/delivery-rules'
    | '/app/employees'
    | '/app/inventory'
    | '/app/items'
    | '/app/roles-teams'
    | '/app/sales'
    | '/app/schedule-compliance'
    | '/app/schedule-history'
    | '/app/schedule-templates'
    | '/app/schedules'
    | '/app/shifts'
    | '/app/time-entries'
    | '/app/units'
    | '/api/public/sales-ingest'
    | '/api/public/stripe-webhook'
    | '/portal/cartao-ponto/$id'
    | '/portal/documentos/$id'
    | '/portal/holerites/$id'
    | '/portal/itens/$id'
    | '/app'
    | '/portal/cartao-ponto'
    | '/portal/documentos'
    | '/portal/holerites'
    | '/portal/itens'
    | '/app/conformidade/kits'
    | '/app/conformidade/pendencias'
    | '/app/conformidade/trocas'
    | '/app/deliveries/$id'
    | '/app/point-cards/$id'
    | '/app/settings/aceite'
    | '/app/settings/lgpd'
    | '/portal/holerites/$id/comprovante'
    | '/app/conformidade'
    | '/app/deliveries'
    | '/app/point-cards'
    | '/app/conformidade/exames/$id'
    | '/app/conformidade/exames/novo'
    | '/app/documentos/holerites/$id'
    | '/app/conformidade/exames'
    | '/app/documentos/holerites'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/portal/escala'
    | '/portal/login'
    | '/portal/pendencias'
    | '/portal/perfil'
    | '/portal/ponto'
    | '/portal/'
    | '/_authenticated/app/delivery-rules'
    | '/_authenticated/app/employees'
    | '/_authenticated/app/inventory'
    | '/_authenticated/app/items'
    | '/_authenticated/app/roles-teams'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/schedule-compliance'
    | '/_authenticated/app/schedule-history'
    | '/_authenticated/app/schedule-templates'
    | '/_authenticated/app/schedules'
    | '/_authenticated/app/shifts'
    | '/_authenticated/app/time-entries'
    | '/_authenticated/app/units'
    | '/api/public/sales-ingest'
    | '/api/public/stripe-webhook'
    | '/portal/cartao-ponto/$id'
    | '/portal/documentos/$id'
    | '/portal/holerites/$id'
    | '/portal/itens/$id'
    | '/_authenticated/app/'
    | '/portal/cartao-ponto/'
    | '/portal/documentos/'
    | '/portal/holerites/'
    | '/portal/itens/'
    | '/_authenticated/app/conformidade/kits'
    | '/_authenticated/app/conformidade/pendencias'
    | '/_authenticated/app/conformidade/trocas'
    | '/_authenticated/app/deliveries/$id'
    | '/_authenticated/app/point-cards/$id'
    | '/_authenticated/app/settings/aceite'
    | '/_authenticated/app/settings/lgpd'
    | '/portal/holerites/$id/comprovante'
    | '/_authenticated/app/conformidade/'
    | '/_authenticated/app/deliveries/'
    | '/_authenticated/app/point-cards/'
    | '/_authenticated/app/conformidade/exames/$id'
    | '/_authenticated/app/conformidade/exames/novo'
    | '/_authenticated/app/documentos/holerites/$id'
    | '/_authenticated/app/conformidade/exames/'
    | '/_authenticated/app/documentos/holerites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRouteWithChildren
  ApiPublicSalesIngestRoute: typeof ApiPublicSalesIngestRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/escala': {
      id: '/portal/escala'
      path: '/escala'
      fullPath: '/portal/escala'
      preLoaderRoute: typeof PortalEscalaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/pendencias': {
      id: '/portal/pendencias'
      path: '/pendencias'
      fullPath: '/portal/pendencias'
      preLoaderRoute: typeof PortalPendenciasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/perfil': {
      id: '/portal/perfil'
      path: '/perfil'
      fullPath: '/portal/perfil'
      preLoaderRoute: typeof PortalPerfilRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/ponto': {
      id: '/portal/ponto'
      path: '/ponto'
      fullPath: '/portal/ponto'
      preLoaderRoute: typeof PortalPontoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/delivery-rules': {
      id: '/_authenticated/app/delivery-rules'
      path: '/delivery-rules'
      fullPath: '/app/delivery-rules'
      preLoaderRoute: typeof AuthenticatedAppDeliveryRulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/employees': {
      id: '/_authenticated/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AuthenticatedAppEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory': {
      id: '/_authenticated/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/items': {
      id: '/_authenticated/app/items'
      path: '/items'
      fullPath: '/app/items'
      preLoaderRoute: typeof AuthenticatedAppItemsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/roles-teams': {
      id: '/_authenticated/app/roles-teams'
      path: '/roles-teams'
      fullPath: '/app/roles-teams'
      preLoaderRoute: typeof AuthenticatedAppRolesTeamsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/schedule-compliance': {
      id: '/_authenticated/app/schedule-compliance'
      path: '/schedule-compliance'
      fullPath: '/app/schedule-compliance'
      preLoaderRoute: typeof AuthenticatedAppScheduleComplianceRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/schedule-history': {
      id: '/_authenticated/app/schedule-history'
      path: '/schedule-history'
      fullPath: '/app/schedule-history'
      preLoaderRoute: typeof AuthenticatedAppScheduleHistoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/schedule-templates': {
      id: '/_authenticated/app/schedule-templates'
      path: '/schedule-templates'
      fullPath: '/app/schedule-templates'
      preLoaderRoute: typeof AuthenticatedAppScheduleTemplatesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/schedules': {
      id: '/_authenticated/app/schedules'
      path: '/schedules'
      fullPath: '/app/schedules'
      preLoaderRoute: typeof AuthenticatedAppSchedulesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/shifts': {
      id: '/_authenticated/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AuthenticatedAppShiftsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/time-entries': {
      id: '/_authenticated/app/time-entries'
      path: '/time-entries'
      fullPath: '/app/time-entries'
      preLoaderRoute: typeof AuthenticatedAppTimeEntriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/units': {
      id: '/_authenticated/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AuthenticatedAppUnitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/sales-ingest': {
      id: '/api/public/sales-ingest'
      path: '/api/public/sales-ingest'
      fullPath: '/api/public/sales-ingest'
      preLoaderRoute: typeof ApiPublicSalesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/cartao-ponto/': {
      id: '/portal/cartao-ponto/'
      path: '/cartao-ponto'
      fullPath: '/portal/cartao-ponto/'
      preLoaderRoute: typeof PortalCartaoPontoIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cartao-ponto/$id': {
      id: '/portal/cartao-ponto/$id'
      path: '/cartao-ponto/$id'
      fullPath: '/portal/cartao-ponto/$id'
      preLoaderRoute: typeof PortalCartaoPontoIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos/': {
      id: '/portal/documentos/'
      path: '/documentos'
      fullPath: '/portal/documentos/'
      preLoaderRoute: typeof PortalDocumentosIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos/$id': {
      id: '/portal/documentos/$id'
      path: '/documentos/$id'
      fullPath: '/portal/documentos/$id'
      preLoaderRoute: typeof PortalDocumentosIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/holerites/': {
      id: '/portal/holerites/'
      path: '/holerites'
      fullPath: '/portal/holerites/'
      preLoaderRoute: typeof PortalHoleritesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/holerites/$id': {
      id: '/portal/holerites/$id'
      path: '/holerites/$id'
      fullPath: '/portal/holerites/$id'
      preLoaderRoute: typeof PortalHoleritesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/itens/': {
      id: '/portal/itens/'
      path: '/itens'
      fullPath: '/portal/itens/'
      preLoaderRoute: typeof PortalItensIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/itens/$id': {
      id: '/portal/itens/$id'
      path: '/itens/$id'
      fullPath: '/portal/itens/$id'
      preLoaderRoute: typeof PortalItensIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/app/conformidade/': {
      id: '/_authenticated/app/conformidade/'
      path: '/conformidade'
      fullPath: '/app/conformidade/'
      preLoaderRoute: typeof AuthenticatedAppConformidadeIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conformidade/kits': {
      id: '/_authenticated/app/conformidade/kits'
      path: '/conformidade/kits'
      fullPath: '/app/conformidade/kits'
      preLoaderRoute: typeof AuthenticatedAppConformidadeKitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conformidade/pendencias': {
      id: '/_authenticated/app/conformidade/pendencias'
      path: '/conformidade/pendencias'
      fullPath: '/app/conformidade/pendencias'
      preLoaderRoute: typeof AuthenticatedAppConformidadePendenciasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conformidade/trocas': {
      id: '/_authenticated/app/conformidade/trocas'
      path: '/conformidade/trocas'
      fullPath: '/app/conformidade/trocas'
      preLoaderRoute: typeof AuthenticatedAppConformidadeTrocasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deliveries/': {
      id: '/_authenticated/app/deliveries/'
      path: '/deliveries'
      fullPath: '/app/deliveries/'
      preLoaderRoute: typeof AuthenticatedAppDeliveriesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/deliveries/$id': {
      id: '/_authenticated/app/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/app/deliveries/$id'
      preLoaderRoute: typeof AuthenticatedAppDeliveriesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/point-cards/': {
      id: '/_authenticated/app/point-cards/'
      path: '/point-cards'
      fullPath: '/app/point-cards/'
      preLoaderRoute: typeof AuthenticatedAppPointCardsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/point-cards/$id': {
      id: '/_authenticated/app/point-cards/$id'
      path: '/point-cards/$id'
      fullPath: '/app/point-cards/$id'
      preLoaderRoute: typeof AuthenticatedAppPointCardsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/aceite': {
      id: '/_authenticated/app/settings/aceite'
      path: '/settings/aceite'
      fullPath: '/app/settings/aceite'
      preLoaderRoute: typeof AuthenticatedAppSettingsAceiteRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings/lgpd': {
      id: '/_authenticated/app/settings/lgpd'
      path: '/settings/lgpd'
      fullPath: '/app/settings/lgpd'
      preLoaderRoute: typeof AuthenticatedAppSettingsLgpdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/portal/holerites/$id/comprovante': {
      id: '/portal/holerites/$id/comprovante'
      path: '/comprovante'
      fullPath: '/portal/holerites/$id/comprovante'
      preLoaderRoute: typeof PortalHoleritesIdComprovanteRouteImport
      parentRoute: typeof PortalHoleritesIdRoute
    }
    '/_authenticated/app/conformidade/exames/': {
      id: '/_authenticated/app/conformidade/exames/'
      path: '/conformidade/exames'
      fullPath: '/app/conformidade/exames/'
      preLoaderRoute: typeof AuthenticatedAppConformidadeExamesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conformidade/exames/$id': {
      id: '/_authenticated/app/conformidade/exames/$id'
      path: '/conformidade/exames/$id'
      fullPath: '/app/conformidade/exames/$id'
      preLoaderRoute: typeof AuthenticatedAppConformidadeExamesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/conformidade/exames/novo': {
      id: '/_authenticated/app/conformidade/exames/novo'
      path: '/conformidade/exames/novo'
      fullPath: '/app/conformidade/exames/novo'
      preLoaderRoute: typeof AuthenticatedAppConformidadeExamesNovoRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos/holerites/': {
      id: '/_authenticated/app/documentos/holerites/'
      path: '/documentos/holerites'
      fullPath: '/app/documentos/holerites/'
      preLoaderRoute: typeof AuthenticatedAppDocumentosHoleritesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documentos/holerites/$id': {
      id: '/_authenticated/app/documentos/holerites/$id'
      path: '/documentos/holerites/$id'
      fullPath: '/app/documentos/holerites/$id'
      preLoaderRoute: typeof AuthenticatedAppDocumentosHoleritesIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppDeliveryRulesRoute: typeof AuthenticatedAppDeliveryRulesRoute
  AuthenticatedAppEmployeesRoute: typeof AuthenticatedAppEmployeesRoute
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRoute
  AuthenticatedAppItemsRoute: typeof AuthenticatedAppItemsRoute
  AuthenticatedAppRolesTeamsRoute: typeof AuthenticatedAppRolesTeamsRoute
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRoute
  AuthenticatedAppScheduleComplianceRoute: typeof AuthenticatedAppScheduleComplianceRoute
  AuthenticatedAppScheduleHistoryRoute: typeof AuthenticatedAppScheduleHistoryRoute
  AuthenticatedAppScheduleTemplatesRoute: typeof AuthenticatedAppScheduleTemplatesRoute
  AuthenticatedAppSchedulesRoute: typeof AuthenticatedAppSchedulesRoute
  AuthenticatedAppShiftsRoute: typeof AuthenticatedAppShiftsRoute
  AuthenticatedAppTimeEntriesRoute: typeof AuthenticatedAppTimeEntriesRoute
  AuthenticatedAppUnitsRoute: typeof AuthenticatedAppUnitsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppConformidadeKitsRoute: typeof AuthenticatedAppConformidadeKitsRoute
  AuthenticatedAppConformidadePendenciasRoute: typeof AuthenticatedAppConformidadePendenciasRoute
  AuthenticatedAppConformidadeTrocasRoute: typeof AuthenticatedAppConformidadeTrocasRoute
  AuthenticatedAppDeliveriesIdRoute: typeof AuthenticatedAppDeliveriesIdRoute
  AuthenticatedAppPointCardsIdRoute: typeof AuthenticatedAppPointCardsIdRoute
  AuthenticatedAppSettingsAceiteRoute: typeof AuthenticatedAppSettingsAceiteRoute
  AuthenticatedAppSettingsLgpdRoute: typeof AuthenticatedAppSettingsLgpdRoute
  AuthenticatedAppConformidadeIndexRoute: typeof AuthenticatedAppConformidadeIndexRoute
  AuthenticatedAppDeliveriesIndexRoute: typeof AuthenticatedAppDeliveriesIndexRoute
  AuthenticatedAppPointCardsIndexRoute: typeof AuthenticatedAppPointCardsIndexRoute
  AuthenticatedAppConformidadeExamesIdRoute: typeof AuthenticatedAppConformidadeExamesIdRoute
  AuthenticatedAppConformidadeExamesNovoRoute: typeof AuthenticatedAppConformidadeExamesNovoRoute
  AuthenticatedAppDocumentosHoleritesIdRoute: typeof AuthenticatedAppDocumentosHoleritesIdRoute
  AuthenticatedAppConformidadeExamesIndexRoute: typeof AuthenticatedAppConformidadeExamesIndexRoute
  AuthenticatedAppDocumentosHoleritesIndexRoute: typeof AuthenticatedAppDocumentosHoleritesIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppDeliveryRulesRoute: AuthenticatedAppDeliveryRulesRoute,
  AuthenticatedAppEmployeesRoute: AuthenticatedAppEmployeesRoute,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRoute,
  AuthenticatedAppItemsRoute: AuthenticatedAppItemsRoute,
  AuthenticatedAppRolesTeamsRoute: AuthenticatedAppRolesTeamsRoute,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRoute,
  AuthenticatedAppScheduleComplianceRoute:
    AuthenticatedAppScheduleComplianceRoute,
  AuthenticatedAppScheduleHistoryRoute: AuthenticatedAppScheduleHistoryRoute,
  AuthenticatedAppScheduleTemplatesRoute:
    AuthenticatedAppScheduleTemplatesRoute,
  AuthenticatedAppSchedulesRoute: AuthenticatedAppSchedulesRoute,
  AuthenticatedAppShiftsRoute: AuthenticatedAppShiftsRoute,
  AuthenticatedAppTimeEntriesRoute: AuthenticatedAppTimeEntriesRoute,
  AuthenticatedAppUnitsRoute: AuthenticatedAppUnitsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppConformidadeKitsRoute: AuthenticatedAppConformidadeKitsRoute,
  AuthenticatedAppConformidadePendenciasRoute:
    AuthenticatedAppConformidadePendenciasRoute,
  AuthenticatedAppConformidadeTrocasRoute:
    AuthenticatedAppConformidadeTrocasRoute,
  AuthenticatedAppDeliveriesIdRoute: AuthenticatedAppDeliveriesIdRoute,
  AuthenticatedAppPointCardsIdRoute: AuthenticatedAppPointCardsIdRoute,
  AuthenticatedAppSettingsAceiteRoute: AuthenticatedAppSettingsAceiteRoute,
  AuthenticatedAppSettingsLgpdRoute: AuthenticatedAppSettingsLgpdRoute,
  AuthenticatedAppConformidadeIndexRoute:
    AuthenticatedAppConformidadeIndexRoute,
  AuthenticatedAppDeliveriesIndexRoute: AuthenticatedAppDeliveriesIndexRoute,
  AuthenticatedAppPointCardsIndexRoute: AuthenticatedAppPointCardsIndexRoute,
  AuthenticatedAppConformidadeExamesIdRoute:
    AuthenticatedAppConformidadeExamesIdRoute,
  AuthenticatedAppConformidadeExamesNovoRoute:
    AuthenticatedAppConformidadeExamesNovoRoute,
  AuthenticatedAppDocumentosHoleritesIdRoute:
    AuthenticatedAppDocumentosHoleritesIdRoute,
  AuthenticatedAppConformidadeExamesIndexRoute:
    AuthenticatedAppConformidadeExamesIndexRoute,
  AuthenticatedAppDocumentosHoleritesIndexRoute:
    AuthenticatedAppDocumentosHoleritesIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortalHoleritesIdRouteChildren {
  PortalHoleritesIdComprovanteRoute: typeof PortalHoleritesIdComprovanteRoute
}

const PortalHoleritesIdRouteChildren: PortalHoleritesIdRouteChildren = {
  PortalHoleritesIdComprovanteRoute: PortalHoleritesIdComprovanteRoute,
}

const PortalHoleritesIdRouteWithChildren =
  PortalHoleritesIdRoute._addFileChildren(PortalHoleritesIdRouteChildren)

interface PortalRouteChildren {
  PortalEscalaRoute: typeof PortalEscalaRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalPendenciasRoute: typeof PortalPendenciasRoute
  PortalPerfilRoute: typeof PortalPerfilRoute
  PortalPontoRoute: typeof PortalPontoRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalCartaoPontoIdRoute: typeof PortalCartaoPontoIdRoute
  PortalDocumentosIdRoute: typeof PortalDocumentosIdRoute
  PortalHoleritesIdRoute: typeof PortalHoleritesIdRouteWithChildren
  PortalItensIdRoute: typeof PortalItensIdRoute
  PortalCartaoPontoIndexRoute: typeof PortalCartaoPontoIndexRoute
  PortalDocumentosIndexRoute: typeof PortalDocumentosIndexRoute
  PortalHoleritesIndexRoute: typeof PortalHoleritesIndexRoute
  PortalItensIndexRoute: typeof PortalItensIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalEscalaRoute: PortalEscalaRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalPendenciasRoute: PortalPendenciasRoute,
  PortalPerfilRoute: PortalPerfilRoute,
  PortalPontoRoute: PortalPontoRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalCartaoPontoIdRoute: PortalCartaoPontoIdRoute,
  PortalDocumentosIdRoute: PortalDocumentosIdRoute,
  PortalHoleritesIdRoute: PortalHoleritesIdRouteWithChildren,
  PortalItensIdRoute: PortalItensIdRoute,
  PortalCartaoPontoIndexRoute: PortalCartaoPontoIndexRoute,
  PortalDocumentosIndexRoute: PortalDocumentosIndexRoute,
  PortalHoleritesIndexRoute: PortalHoleritesIndexRoute,
  PortalItensIndexRoute: PortalItensIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRouteWithChildren,
  ApiPublicSalesIngestRoute: ApiPublicSalesIngestRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
